# Generated by Django 4.2.4 on 2023-08-14 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_grubbing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grubbing',
            name='date',
            field=models.DateField(verbose_name='grubbing date'),
        ),
    ]
