# Generated by Django 4.2.4 on 2023-08-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_grubbing_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plaything',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='finch',
            name='playthings',
            field=models.ManyToManyField(to='main_app.plaything'),
        ),
    ]
